services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - /Users/samuel/db_volumn/patient_service:/var/lib/postgresql/data
    networks:
      - internal
  
  patient-service:
    build: .
    image: patient-service:latest
    container_name: patient-service-app
    ports:
      - "4000:4000"
    environment:
      - SPRING_DATASOURCE_PASSWORD=password
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
    depends_on:
      - patient-service-db
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge