services:
  billing-service:
      build: .
      image: billing-service:latest
      container_name: billing-service-app
      ports:
        - "4001:4001"
        - "9001:9001"
      networks:
        - internal

networks:
  internal:
    name: internal
    driver: bridge